sunnah_audio_server_config:
  port: 8990
  host: "127.0.0.1"

jwt_auth_config:
  secret: "O07G947TB8B2XUU2QXA0I9DK9Q19C2"
  token_expiration_time: 3 #in days

postgres:
  username: "postgres"
  password: "password"
  host: "localhost"
  port: 5432
  database_name: "shunku_middleware"

mysql:
  username: "admin"
  password: "password"
  host: "localhost"
  port: 3306
  database_name: "muryar_sunnah"

redis:
  host: "localhost"
  port: 6379
  password:

rabbitmq:
  url: "amqp://guest:guest@localhost:5672"

smtp:
  host: "sandbox.smtp.mailtrap.io"
  port: 2525
  username: "eb6e9e3571c28d"
  password: "2ecb04dfb23a0c"
  from_email: "noreply@muryarsunnah.com"
  from_name: "Muryar Sunnah"