sunnah_audio_server_config:
  port: 8990
  host: "0.0.0.0"
  base_url: "https://www.muryarsunnah.com"

jwt_auth_config:
  secret: "YOUR_PRODUCTION_JWT_SECRET_HERE"
  token_expiration_time: 7 #in days

app_paths:
  static_images: "/api/v1/static/images"
  static_uploads: "/api/v1/static/audio"
  static_audio: "/api/v1/static/audio"
  images_dir: "/home/muryarsunnah/htdocs/www.muryarsunnah.com/web/images"
  uploads_dir: "/home/muryarsunnah/htdocs/www.muryarsunnah.com/web/uploads"

postgres:
  username: "your_db_username"
  password: "your_db_password"
  host: "localhost"
  port: 5432
  database_name: "muryar_sunnah"

mysql:
  username: "your_mysql_username"
  password: "your_mysql_password"
  host: "localhost"
  port: 3306
  database_name: "muryar_sunnah"

redis:
  host: "localhost"
  port: 6379
  password: "your_redis_password"

rabbitmq:
  url: "amqp://guest:guest@localhost:5672"

smtp:
  host: "your_smtp_host"
  port: 587
  username: "your_smtp_username"
  password: "your_smtp_password"
  from_email: "noreply@muryarsunnah.com"
  from_name: "Muryar Sunnah"