sunnah_audio_server_config:
  port: 8990
  host: "0.0.0.0"
  base_url: "https://www.muryarsunnah.com"

jwt_auth_config:
  secret: "erLh6Yv67dyvjycgbZB2vspPIymhB7zVCZM6k8Lu8mjdduP8rQ"
  token_expiration_time: 3 #in days

app_paths:
  static_images: "/api/v1/static/images"
  static_uploads: "/api/v1/static/audio"
  static_audio: "/api/v1/static/audio"
  images_dir: "/home/muryarsunnah/htdocs/www.muryarsunnah.com/web/images"
  uploads_dir: "/home/muryarsunnah/htdocs/www.muryarsunnah.com/web/uploads"

mysql:
  username: "muryarsunnah"
  password: "tBJvu2CTyggJMscFTsJx"
  host: "localhost"
  port: 3306
  database_name: "muryarsunnah"

redis:
  host: "localhost"
  port: 6379
  password:

rabbitmq:
  url: "amqp://guest:guest@localhost:5672"

smtp:
  host: "your_smtp_host"
  port: 587
  username: "your_smtp_username"
  password: "your_smtp_password"
  from_email: "noreply@muryarsunnah.com"
  from_name: "Muryar Sunnah"